device_info:
  device:
    name: realman_robot
  manufacturer:
    name: RealMan Intelligent Technology
    uuid: 6250ed9f-36fc-4157-9fc5-745e8124d64d
  model:
    name: RML63
    uuid: 427c0df6-429a-427f-abcf-eef67ac60297
  user_description: Realman Robotics RML63 Robot
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: robot
        uuid: 39b513e7-21b9-4b49-8654-7537473030eb
      subclasses: 
        - serial
        - serial_six_axis
        - cobot
  implemented_types:
    - com.robotraconteur.robotics.robot.Robot
robot_type: serial
robot_capabilities:
- jog_command
- trajectory_command
- position_command

# https://github.com/RealManRobot/ros2_rm_robot/blob/main/rm_description/urdf/rm_63.urdf
chains:
- kin_chain_identifier: robot_arm
  H:
  - x: 0.0
    y: 0.0
    z: 1.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 1.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 1.0
  P:
  - x:  0.0
    y:  0.0
    z:  0.172
  - x:  -0.086
    y:  0.0
    z:  0.0
  - x:  0
    y:  -0.00030011
    z:  0.38
  - x:  0.069
    y:  0.0003
    z:  0.4045
  - x:  0.0
    y:  0.0
    z:  0.0
  - x:  0.0
    y:  0.0
    z:  0.1145
  - x:  0.0
    y:  0.0
    z:  0.0


  # flange_identifier: tool0
  # flange_pose:
  #   orientation:
  #     w: 0.0
  #     x: 0.0
  #     y: 0.0
  #     z: 0.0
  #   position:
  #     x: 0.0
  #     y: 0.0
  #     z: 0.0
  joint_numbers:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  link_identifiers:
  - base_link
  - link1
  - link2
  - link3
  - link4
  - link5
  - link6
joint_info:
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint1
  joint_limits:
    effort: 1.0
    lower: -3.1
    upper: 3.1
    velocity: 1.0
    acceleration: 1.0
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint2
  joint_limits:
    effort: 1.0
    lower: -3.1
    upper: 3.1
    velocity: 1.0
    acceleration: 1.0
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint3
  joint_limits:
    effort: 1.0
    lower: -3.1
    upper: 2.53
    velocity: 1.0
    acceleration: 1.0
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint4
  joint_limits:
    effort: 1.0
    lower: -3.1
    upper: 3.1
    velocity: 1.0
    acceleration: 1.0
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint5
  joint_limits:
    effort: 1.0
    lower: -3.1
    upper: 3.1
    velocity: 1.0
    acceleration: 1.0
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint6
  joint_limits:
    effort: 1.0
    lower: -6.28
    upper: 6.28
    velocity: 1.0
    acceleration: 1.0
  joint_type: revolute
  passive: false
